Vagrant.configure("2") do |config|
  #config.vm.network "public_network", bridge: "enp7s0"
  config.vm.provision "shell", inline: <<-SHELL
  yum install nginx -y
  yum install bash-completion -y
  sed -i '/#/d' /etc/nginx/nginx.conf
  systemctl enable --now nginx.service 
  mkdir -p /etc/ssl
  openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/privateKey.key -out /etc/ssl/certificate.crt -subj "/C=US/ST=TEST/L=TEST/O=TEST/CN=www.example.com"
	SHELL
  

  config.vm.define "proxy" do |proxy|
    proxy.vm.box = "boxomatic/centos-8-stream"
    proxy.vm.network "public_network", bridge: "enp7s0", ip: '192.168.33.143'
    #proxy.vm.network "public_network",
    #proxy.vm.network "forwarded_port", guest: 22, host: 2222
    #proxy.vm.network "forwarded_port", guest: 80, host: 8080
    #proxy.vm.network "forwarded_port", guest: 443, host: 3443

    proxy.vm.provision "shell", inline: <<-SHELL
      cat << CMD > /etc/nginx/nginx.conf
      user nginx;
      worker_processes auto;
      error_log /var/log/nginx/error.log;
      pid /run/nginx.pid;
      
      include /usr/share/nginx/modules/*.conf;
      
      events {
          worker_connections 1024;
      }
      
      http {
          log_format  main  '\\$remote_addr - \\$remote_user [\\$time_local] "\\$request" '
                            '\\$status \\$body_bytes_sent "\\$http_referer" '
                            '"\\$http_user_agent" "\\$http_x_forwarded_for"';
      
          access_log  /var/log/nginx/access.log  main;
      
          sendfile            on;
          tcp_nopush          on;
          tcp_nodelay         on;
          keepalive_timeout   65;
          types_hash_max_size 2048;
      
          include             /etc/nginx/mime.types;
          default_type        application/octet-stream;
      
          include /etc/nginx/conf.d/*.conf;
      
      
          server {
              listen       80 default_server;
              server_name  _;
              root         /usr/share/nginx/html;
      
              include /etc/nginx/default.d/*.conf;
      
              location / {
              }
      
              error_page 404 /404.html;
                  location = /40x.html {
              }
      
              error_page 500 502 503 504 /50x.html;
                  location = /50x.html {
              }
          }
       
      server {
              listen       80;
              server_name  test-admin.local.net;
              root         /usr/share/nginx/html;
      
              include /etc/nginx/default.d/*.conf;
                location / {
                        proxy_pass "https://192.168.33.66";
                        proxy_set_header Host \\$host;
                        proxy_set_header X-Real-IP \\$remote_addr;
                }
           error_page 404 /404.html;
                  location = /40x.html {
              }
      
              error_page 500 502 503 504 /50x.html;
                  location = /50x.html {
              }
        }
      
          server {
              listen       443;
              server_name  test-admin.local.net;
              root         /usr/share/nginx/html;
        
              ssl on;
              ssl_certificate /etc/ssl/certificate.crt;
              ssl_certificate_key /etc/ssl/privateKey.key;
      
              include /etc/nginx/default.d/*.conf;
              location / {
          proxy_pass "https://192.168.33.66";
          proxy_set_header Host \\$host;
          proxy_set_header X-Real-IP \\$remote_addr;
              }
              error_page 404 /404.html;
                  location = /40x.html {
              }
      
              error_page 500 502 503 504 /50x.html;
                  location = /50x.html {
              }
          }
      }
CMD
	    #sed -i -e  '\/location \\/\/a proxy_pass "https://192.168.33.66";' \
      #  -e '\/location \\/\/a proxy_set_header X-Real-IP $remote_addr;' \
      #  -e '\/location \\/\/a proxy_set_header Host $host;' 
      #  -e'\/server {\/a ssl on;'
      #  -e'\/server {\/a ssl onssl_certificate /etc/ssl/certificate.crt;'
      #  -e'\/server {\/a ssl_certificate_key /etc/ssl/privateKey.key;' /etc/nginx/nginx.conf
      systemctl restart nginx.service 
    SHELL
  end

  config.vm.define "web" do |web|
    web.vm.box = "boxomatic/centos-8-stream"
    web.vm.network "public_network", bridge: "enp7s0", ip: '192.168.33.66'
    #web.vm.network "forwarded_port", guest: 22, host: 2200
    #web.vm.network "forwarded_port", guest: 80, host: 8070
    #web.vm.network "forwarded_port", guest: 443, host: 4443
    web.vm.provision "shell", inline: <<-SHELL
      sed -i -e '\/server \{\/a real_ip_header X-Real-IP;' \
             -e'\/server {\/a set_real_ip_from 192.168.33.143;' \
             -e'\/server {\/a ssl on;' \
             -e'\/server {\/a ssl_certificate /etc/ssl/certificate.crt;' \
             -e'\/server {\/a ssl_certificate_key /etc/ssl/privateKey.key;' \
             -e 's/server_name  _/server_name  test-admin.local.net/g' \
             -e 's/listen       80/listen 443/g' /etc/nginx/nginx.conf
      echo 'TEST' > /usr/share/nginx/html/index.html
      systemctl restart nginx.service 
	  SHELL
  end
end
